
package com.mycompany.tarea3;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import com.mycompany.tarea3.DBAccess;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class VistaProducto extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public VistaProducto() throws SQLException {
        initComponents();
        getProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        skuInput = new javax.swing.JTextField();
        nombreInput = new javax.swing.JTextField();
        precioInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        ofertaInput = new javax.swing.JTextField();
        stockInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pesoInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 3");

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));

        skuInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skuInputActionPerformed(evt);
            }
        });
        skuInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                skuInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                skuInputKeyReleased(evt);
            }
        });

        nombreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInputActionPerformed(evt);
            }
        });
        nombreInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreInputKeyReleased(evt);
            }
        });

        precioInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioInputActionPerformed(evt);
            }
        });
        precioInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioInputKeyReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SKU");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        updateButton.setText("Editar");
        updateButton.setEnabled(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        addButton.setText("Agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        ofertaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaInputActionPerformed(evt);
            }
        });
        ofertaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ofertaInputKeyReleased(evt);
            }
        });

        stockInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockInputActionPerformed(evt);
            }
        });
        stockInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockInputKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Oferta (Opcional)");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Stock");

        pesoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoInputActionPerformed(evt);
            }
        });
        pesoInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesoInputKeyReleased(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Peso (Opcional)");

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Administrar Usuarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(precioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ofertaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(stockInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(skuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(291, 291, 291)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(pesoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(skuInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton)
                            .addComponent(addButton)
                            .addComponent(deleteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ofertaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKU", "Nombre", "Precio", "Oferta", "Stock", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonas);

        jPanel2.setBackground(new java.awt.Color(211, 211, 211));

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchInputKeyReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Buscador por SKU o Nombre");

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonasMouseClicked
        // TODO add your handling code here:
        int row = this.jTablePersonas.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        
        Object cedula = model.getValueAt(row, 0);
        Object nombre = model.getValueAt(row, 1);
        Object apellido = model.getValueAt(row, 2);
        
        this.skuInput.setText(cedula.toString());
        this.nombreInput.setText(nombre.toString());
        this.precioInput.setText(apellido.toString());
        
        this.validateButton();
        
    }//GEN-LAST:event_jTablePersonasMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        String sku = this.skuInput.getText();
        String nombre = this.nombreInput.getText();
        String precio = this.precioInput.getText();
        String oferta = this.ofertaInput.getText();
        String stock = this.stockInput.getText();
        String peso = this.pesoInput.getText();
        
        if(peso.length() == 0){
            peso = "0";
        }
        
        if(oferta.length() == 0){
            oferta = "0";
        }
        
        System.out.println(oferta);
        System.out.println(peso);
        
        this.addProducto(
            sku, 
            nombre, 
            Double.parseDouble(precio),
            Double.parseDouble(oferta),
            Integer.parseInt(stock),
            Double.parseDouble(peso)
        );
        this.getProductos();
    }//GEN-LAST:event_addButtonActionPerformed

    private void skuInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skuInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skuInputActionPerformed

    private void skuInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_skuInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_skuInputKeyPressed

    private void skuInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_skuInputKeyReleased
        // TODO add your handling code here:
        this.validateButton();
    }//GEN-LAST:event_skuInputKeyReleased

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
        String sku = this.skuInput.getText();
        String nombre = this.nombreInput.getText();
        String precio = this.precioInput.getText();
        String oferta = this.ofertaInput.getText();
        String stock = this.stockInput.getText();
        String peso = this.pesoInput.getText();
        
        if(peso.length() == 0){
            peso = "0";
        }
        
        if(oferta.length() == 0){
            oferta = "0";
        }
        
        System.out.println(oferta);
        System.out.println(peso);
        
        this.updateProducto(
            sku, 
            nombre, 
            Double.parseDouble(precio),
            Double.parseDouble(oferta),
            Integer.parseInt(stock),
            Double.parseDouble(peso)
        );
        this.getProductos();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        this.deleteProducto(this.skuInput.getText());
        this.getProductos();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void nombreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInputActionPerformed

    private void precioInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioInputActionPerformed

    private void nombreInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreInputKeyReleased
        // TODO add your handling code here:
        this.validateButton();
    }//GEN-LAST:event_nombreInputKeyReleased

    private void precioInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioInputKeyReleased
        // TODO add your handling code here:
        this.validateButton();
    }//GEN-LAST:event_precioInputKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String text = this.searchInput.getText();
        this.searchButton.setEnabled(true);
        if (text.length() > 0){
            this.getProductosByText(text);
        } else {
            this.getProductos();
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyReleased
        // TODO add your handling code here:

        String text = this.searchInput.getText();

        if(text.length() == 0){
            this.getProductos();
        }
    }//GEN-LAST:event_searchInputKeyReleased

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputKeyPressed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void ofertaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaInputActionPerformed

    private void ofertaInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ofertaInputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaInputKeyReleased

    private void stockInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockInputActionPerformed

    private void stockInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockInputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_stockInputKeyReleased

    private void pesoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoInputActionPerformed

    private void pesoInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoInputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoInputKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new VistaInicio().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            new Vista().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(VistaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaProducto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VistaProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonas;
    private javax.swing.JTextField nombreInput;
    private javax.swing.JTextField ofertaInput;
    private javax.swing.JTextField pesoInput;
    private javax.swing.JTextField precioInput;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextField skuInput;
    private javax.swing.JTextField stockInput;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    
    
    /*
     * CODIGO PERSONALIZADO 
     */
       
    //Traer lista de usuarios
    public void getProductos(){
        
        DBAccess db = DBAccess.getConnection();
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        try{
            this.clearTable();
            rs = db.execute("SELECT sku, nombre, precio, oferta, stock, peso FROM producto;");
            while(rs.next()){
                
                System.out.println(rs.getString(1));
                System.out.println(rs.getString(2));
                System.out.println(rs.getString(3));
                System.out.println(rs.getString(4));
                System.out.println(rs.getString(5));
                System.out.println(rs.getString(6));
                
                Object[] row = {
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getDouble(3),
                    rs.getDouble(4),
                    rs.getDouble(5),
                    rs.getDouble(6)
                };
                model.addRow(row);
            }
            this.validateButton();
            rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            db.close();
        }
        
    }
    
        //Traer lista de usuarios
    public void getProductosByText(String text){
        
        DBAccess db = DBAccess.getConnection();
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        
        try{
            this.clearTable();
            rs = db.execute("SELECT sku, nombre, precio, oferta, stock, peso FROM producto WHERE sku = '"+text+"' OR nombre LIKE '%"+text+"%';");
            while(rs.next()){
                Object[] row = {
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getDouble(3),
                    rs.getDouble(4),
                    rs.getDouble(5),
                    rs.getDouble(6)
                };
                model.addRow(row);
            }
            rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            db.close();
        }
        
    }
        
    //Crear nuevos usuarios
    public void addProducto(String sku, String nombre, Double precio, Double oferta, Integer stock, Double peso){
        DBAccess db = DBAccess.getConnection();
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        try{
            db.update("INSERT INTO producto (sku, nombre, precio, oferta, stock, peso) VALUES "
                    + "('"+sku+"','"+nombre+"',"+precio+", "+oferta+", "+stock+", "+peso+");");
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            db.close();
        }
    }
    
    //Actualizar usuario
    public void updateProducto(String sku, String nombre, Double precio, Double oferta, Integer stock, Double peso){
        DBAccess db = DBAccess.getConnection();
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        try{
            db.update("UPDATE producto "
                    + "SET nombre = '"+nombre+"', "
                        + "precio = "+precio+","
                        + "oferta = "+oferta+","
                        + "stock = "+stock+","
                        + "peso = "+peso
                    + "WHERE sku = '"+sku+"';");
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            db.close();
        }
    }
    
    //Eliminar usuario
    public void deleteProducto(String sku){
        DBAccess db = DBAccess.getConnection();
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        try{
            db.update("DELETE FROM producto WHERE sku = '"+sku+"'");
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            db.close();
        }
    }
    
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        int rows = model.getRowCount();
        for(int i = 0; i < rows; i++){
            model.removeRow(0);
        }
    }
    
    public void validateButton(){
        
        String sku = this.skuInput.getText();
        String nombre = this.nombreInput.getText();
        String precio = this.precioInput.getText();
        DefaultTableModel model = (DefaultTableModel) this.jTablePersonas.getModel();
        int rows = model.getRowCount();
        //Reviso todas las filas a ver si existe la cedula
        for(int i = 0; i < rows; i++){
            if(sku.equals(model.getValueAt(i, 0))){
                addButton.setEnabled(false);
                updateButton.setEnabled(true);
                deleteButton.setEnabled(true);
                return;
            }
        }
        
        //Si no existe la cedula, reviso que todos los valores esten escritos
        if(sku.length() == 0 || nombre.length() == 0 || precio.length() == 0){
            addButton.setEnabled(false);
            updateButton.setEnabled(false);
            deleteButton.setEnabled(false);
        }else{
            addButton.setEnabled(true);
            updateButton.setEnabled(false);
            deleteButton.setEnabled(false);
        }
        
    }
    
}
